### ISSUE TITLE
[tg tool] some of testgen.h do not contains all necessary methods

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#12]
For example for https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loop-invariants/eq1.c
['/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg', '--keys', '15269,15339,3673,2481', 'eq1.smt2']

tg tool returns 7 headers but 3 out of 7 testgen.h contain all four nondet_XXXX methods. 
Some of them contain only 3 nondet_XXXX methods.
For example for testgen_0.h there is no method nondet_2481
such code doesn't not compile 
"main.c:18:9: error: implicit declaration of function 'nondet_2481'"

Looks like this method was never called during runtime for this test, but it is needed for coverage
If added empty method to testgen.h than coverage is following
![image](https://user-images.githubusercontent.com/16242682/129131138-1ad088b5-4f0e-4c87-a634-c3d0d282bb7e.png)

**Comment by izlatkin** [comment]
absent methods could be added as
const int nondet_XXXX(){
return rand();
}

**Comment by grigoryfedyukovich** [comment]
Thanks, will do!

**Comment by izlatkin** [comment]
[eq1.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6977554/eq1.smt2.txt)

**Comment by izlatkin** [comment]
Similar behavior for https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loops/terminator_02-2.c

/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --keys 4630,4657,14364 terminator_02-2.smt2

[terminator_02-2.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6978320/terminator_02-2.smt2.txt)
`tg` generates 9 tests, none of them contains all 3 nondet_XXXX methods. 
Some of the headers are empty and contain only `#include <stdlib.h>`

**Comment by grigoryfedyukovich** [comment]
Should be fixed in the new commit

**Comment by izlatkin** [comment]
looks good 
![image](https://user-images.githubusercontent.com/16242682/130358584-db563255-af4b-4291-92cd-1dd33ca743fc.png)
