### ISSUE TITLE
[Segmentation fault: 11] for insertion_sort-1.smt2

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#13]
tg tool returns Segmentation fault: 11
for file 
https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loops/insertion_sort-1.c

/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --keys 19641,6306 insertion_sort-1.smt2

`$ /Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --keys 19641,6306 insertion_sort-1.smt2
outgs from main@_shadow.mem.0.0:
     (0)  -> main@_shadow.mem.0.1
     (3)  -> main@_shadow.mem.0.0
outgs from main@_shadow.mem.0.1:
     (1)  -> main@_ret
     (4)  -> main@_shadow.mem.0.2
outgs from main@_shadow.mem.0.2:
     (2)  -> main@_20
     (5)  -> main@_shadow.mem.0.1
outgs from main@_20:
     (6)  -> main@_shadow.mem.0.1
     (8)  -> main@_shadow.mem.0.2
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=0)
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=0)
ARRCAND FROM DATA 1: ([+    -_FH_3    select(_FH_1, _FH_0+(4*_FH_2))    _FH_5]=0)
ARRCAND FROM DATA 1: (_FH_5=(_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2)))))
ARRCAND FROM DATA 1: (_FH_5=((-_FH_3)+select(_FH_1, _FH_0+(4*_FH_2))))
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))]=1)
ARRCAND FROM DATA 2: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=0)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_2    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_2))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=(_FH_2+-1))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=((-_FH_2)+1))
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_4)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2]=(-_FH_4))
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_2)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_4]=(-_FH_2))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=0)
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=0)
ARRCAND FROM DATA 1: ([+    -_FH_3    select(_FH_1, _FH_0+(4*_FH_2))    _FH_5]=0)
ARRCAND FROM DATA 1: (_FH_5=(_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2)))))
ARRCAND FROM DATA 1: (_FH_5=((-_FH_3)+select(_FH_1, _FH_0+(4*_FH_2))))
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))]=1)
ARRCAND FROM DATA 2: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=0)
ARRCAND FROM DATA 2: ([+    _FH_2    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_4)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_2    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_2))
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_2    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_4))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=(_FH_2+-1))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=((-_FH_2)+1))
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_4)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2]=(-_FH_4))
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_2)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_4]=(-_FH_2))
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=1)
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=0)
ARRCAND FROM DATA 2: ([+    _FH_2    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_4)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2    -_FH_5]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_5    -_FH_2    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_2))
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_5    -_FH_2    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_4))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    _FH_2    _FH_5    -1])
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    -_FH_2    -_FH_5    1])
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_2]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=0)
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_2]=(-1*_FH_4))
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_5    _FH_2]=-1)
ARRCAND FROM DATA 2: ([+    _FH_2    _FH_3    -_FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_2))
ARRCAND FROM DATA 2: ([+    _FH_2    _FH_3    -_FH_5    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_4))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    _FH_5    -1*_FH_2    1])
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    -_FH_5    _FH_2    -1])
ARRCAND FROM DATA 1: ([+    _FH_2    _FH_3    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_4]=0)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_2    -_FH_5    _FH_4]=0)
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    _FH_2    _FH_5    -1*_FH_4])
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    -_FH_2    -_FH_5    _FH_4])
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_4    _FH_5    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_2]=0)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_4    -_FH_5    _FH_2]=0)
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    _FH_4    _FH_5    -1*_FH_2])
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    -_FH_4    -_FH_5    _FH_2])
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_4    2*_FH_2]=1)
ARRCAND FROM DATA 2: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_4    2*_FH_2]=_FH_2)
ARRCAND FROM DATA 2: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -1*_FH_4    2*_FH_2]=_FH_4)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    _FH_4    -2*_FH_2]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))    -2*_FH_2]=(-1*_FH_2))
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))    -2*_FH_2]=(-1*_FH_4))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    -1*_FH_4    2*_FH_2    -1])
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=[+    _FH_4    -2*_FH_2    1])
ARRCAND FROM DATA 1: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=1)
ARRCAND FROM DATA 2: ([+    _FH_3    _FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=_FH_2)
ARRCAND FROM DATA 2: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=0)
ARRCAND FROM DATA 1: ([+    _FH_3    -select(_FH_1, _FH_0+(4*_FH_2))    -_FH_4]=-1)
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_2))
ARRCAND FROM DATA 2: ([+    _FH_3    -_FH_4    -select(_FH_1, _FH_0+(4*_FH_2))]=(-1*_FH_4))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=(_FH_4+-1))
ARRCAND FROM DATA 1: ((_FH_3+(-select(_FH_1, _FH_0+(4*_FH_2))))=((-_FH_4)+1))
Segmentation fault: 11`

**Comment by izlatkin** [comment]
[insertion_sort-1.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6976018/insertion_sort-1.smt2.txt)

**Comment by izlatkin** [comment]
same error for https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loops/insertion_sort-2.c

**Comment by grigoryfedyukovich** [comment]
It has arrays, which `tg` does not support.

**Comment by izlatkin** [comment]
Is `tg` going to support them ?

**Comment by izlatkin** [comment]
[log.txt](https://github.com/izlatkin/HornLauncher/files/7042119/log.txt)

```
Failed to marshal: (_FH_0=true)
Assertion failed: (res != NULL), function marshal, file /Users/ilyazlatkin/PycharmProjects/aeval/include/ufo/Smt/ZExprConverter.hpp, line 498.
```

**Comment by grigoryfedyukovich** [comment]
fixed

**Comment by izlatkin** [comment]
fixed. Now coverga is 
Hit: 16
Total: 16
Coverage: 100.0 %

very strange error for test 3

```
./test-coverage 
Bus error: 10

```
not clean what is the source of error
