### ISSUE TITLE
low coverage for sv-benchmarks/c/loops/nec11.c

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#14]
For https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loops/nec11.c
it is expected at least one test with 
`static const int inp_5578[] = {1};`

now 'while' is not covered 
![image](https://user-images.githubusercontent.com/16242682/129219439-f932ce2b-8e8d-49c7-8b2d-e91962cde63a.png)

**Comment by izlatkin** [comment]
[nec11.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6976442/nec11.smt2.txt)

**Comment by grigoryfedyukovich** [comment]
Arrays

**Comment by izlatkin** [comment]
![image](https://user-images.githubusercontent.com/16242682/147261516-509a9ea2-d281-4143-80b1-811017f354b2.png)
fixed
