### ISSUE TITLE
[tg tool] non digit in array inp_3653[] = {1, __loc_var_7, -3653, 0};

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#17]
For c. file https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loop-invariants/const.c
[const.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6979106/const.smt2.txt)
[testgen_3.h.txt](https://github.com/izlatkin/HornLauncher/files/6979108/testgen_3.h.txt)

testgen_3 contains 
`static const int inp_3653[] = {1, **__loc_var_7**, -3653, 0};`

**Comment by izlatkin** [comment]
same problem 
https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loop-zilu/benchmark03_linear.c

[benchmark03_linear.smt2.txt](https://github.com/izlatkin/HornLauncher/files/6984747/benchmark03_linear.smt2.txt)
[testgen.h.txt](https://github.com/izlatkin/HornLauncher/files/6984751/testgen.h.txt)
[Main.c.txt](https://github.com/izlatkin/HornLauncher/files/6984752/Main.c.txt)

**Comment by grigoryfedyukovich** [comment]
Should be fixed in the new commit

**Comment by izlatkin** [comment]
![image](https://user-images.githubusercontent.com/16242682/130357725-09883d83-dcd3-47ef-bddd-e3970d137e15.png)

passed
