### ISSUE TITLE
[tool tg] low coverage for gauss_sum.i.p+lhb-reducer

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#20]
https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loop-new/gauss_sum.i.p%2Blhb-reducer.c
coverage is expected to be higher and covered conditions
`main__sum = main__sum + main__i;
 main__i = main__i + 1;
 label_87:; 
 if (main__i <= main__n)
 {
 main__sum = main__sum + main__i;
 main__i = main__i + 1;
`

[gauss_sum.i.p+lhb-reducer.smt2.txt](https://github.com/izlatkin/HornLauncher/files/7048120/gauss_sum.i.p%2Blhb-reducer.smt2.txt)
[log.txt](https://github.com/izlatkin/HornLauncher/files/7048121/log.txt)
![image](https://user-images.githubusercontent.com/16242682/130818847-320ccd39-2271-43c4-996c-a0678171d1d3.png)

**Comment by grigoryfedyukovich** [comment]
The SMT file has a lot fewer branches than we see in the source code... perhaps because SeaHorn optimized it a lot. Anyway, the coverage should be much better now.

**Comment by izlatkin** [comment]
yes, coverage it definatly better
![image](https://user-images.githubusercontent.com/16242682/132240219-091b2d43-5232-42fb-a510-53c2228d4be0.png)
