### ISSUE TITLE
[tool tg] low coverage for benchmark17_conjunctive

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#21]
For https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loop-zilu/benchmark17_conjunctive.c
coverage is expected to be higher and covered conditions
![image](https://user-images.githubusercontent.com/16242682/130871529-5a3eff1e-fe56-460e-9446-1a4a08c575c8.png)
[benchmark17_conjunctive.smt2.txt](https://github.com/izlatkin/HornLauncher/files/7050305/benchmark17_conjunctive.smt2.txt)
[log.txt](https://github.com/izlatkin/HornLauncher/files/7050307/log.txt)

However, it works fine for very similar c-file
https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loop-zilu/benchmark27_linear.c

**Comment by grigoryfedyukovich** [comment]
should be fixed now

**Comment by izlatkin** [comment]
fixed
![image](https://user-images.githubusercontent.com/16242682/132239038-2ab2985d-cb47-4709-9ced-546a90d11c08.png)
