### ISSUE TITLE
Assertion failed: (varNum >= 0) for count_by_nondet.c

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#28]
see errors in the logs below for c-file https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loop-new/count_by_nondet.c

[count_by_nondet.smt2.txt](https://github.com/izlatkin/HornLauncher/files/7150157/count_by_nondet.smt2.txt)

`/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --inv-mode 0 --no-term --keys 8877 count_by_nondet.smt2
Assertion failed: (varNum >= 0), function exploreTracesTG, file /Users/ilyazlatkin/PycharmProjects/aeval/include/deep/BndExpl.hpp, line 252.
Abort trap: 6
`

it worked before last fix. Also it doesn't work without  `--inv-mode 0 --no-term`

**Comment by izlatkin** [comment]
same issue for loop2-2,  loop4, loop5
` /Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --inv-mode 0 --no-term --keys 4914,3423 loop2-2.smt2
Assertion failed: (varNum >= 0), function exploreTracesTG, file /Users/ilyazlatkin/PycharmProjects/aeval/include/deep/BndExpl.hpp, line 252.
Abort trap: 6
`

`/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --inv-mode 0 --no-term --keys 1453,3412 loop5.smt2
Assertion failed: (varNum >= 0), function exploreTracesTG, file /Users/ilyazlatkin/PycharmProjects/aeval/include/deep/BndExpl.hpp, line 252.
Abort trap: 6
`

```
/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --inv-mode 0 --no-term --keys 1446,3402 loop4.smt2
Assertion failed: (varNum >= 0), function exploreTracesTG, file /Users/ilyazlatkin/PycharmProjects/aeval/include/deep/BndExpl.hpp, line 252.
Abort trap: 6
```

**Comment by izlatkin** [comment]
```
/Users/ilyazlatkin/PycharmProjects/aeval/build/tools/tg/tg --inv-mode 0 --no-term --keys 5253,5286 simple_array_index_value_4.smt2
Assertion failed: (varNum >= 0), function exploreTracesTG, file /Users/ilyazlatkin/PycharmProjects/aeval/include/deep/BndExpl.hpp, line 252.
Abort trap: 6

```

**Comment by grigoryfedyukovich** [comment]
Not reproducible.

**Comment by izlatkin** [comment]
` loop2-2, loop4, loop5` - not supported

**Comment by izlatkin** [comment]
fixed
![image](https://user-images.githubusercontent.com/16242682/147266389-61baf7a6-1280-48f0-a2d8-b374a96c8394.png)
